config/routes.rb
Rails.application.routes.draw do
  mount G5Authenticatable::Engine => '/g5_auth'
  root 'simplifit_users#index'

  get 'register', to: 'simplifit_users#new'

  resources :simplifit_users do
    resources :workouts 
  end

  resources :departments
  resources :workout_categories

  #static pages
  get 'about' => 'pages#about'
end

app/views/layouts/_messages.html.erb
<% flash.each do |msg| %>
  <% if msg[1].is_a?(String) %>
    <div class="alert alert-<%= msg[1] == flash[:notice] ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg[1] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to "G5 SimpliFit", about_path, :class => "navbar-brand" %>
    </li>
    <li>
      <%#= link_to current_user.first_name, user_path(current_user), :class => "navbar-brand" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>G5 SimpliFit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
            <%= render 'layouts/messages' %>
            <%= yield %>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>